version: '3'

volumes:
  pg_data:
  static:
  media:


services:
  db:
    image: postgres:13.0-alpine
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"
        ]
      interval: 3s
      timeout: 3s
      retries: 5

  backend:
    image: 1yunker/volunteers_backend
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/media
    depends_on:
      db:
        condition: service_healthy

  # frontend:
  #   image: 1yunker/volunteers_frontend
  #   command: cp -r /app/result_build/. /static/
  #   volumes:
  #     - static:/static

  gateway:
    image: nginx:1.25.2-alpine3.18-slim
    ports:
      - 8000:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      # - ../docs/:/usr/share/nginx/html/api/docs/
      - static:/static
      - media:/media
    depends_on:
      backend:
        condition: service_started
