name: Build and Push backend Docker image to DockerHub

on:
  workflow_call:

jobs:
  
  build_backend:
    name: Build and Push backend Docker image to DockerHub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          ref: develop
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push to DockerHub
        uses: docker/build-push-action@v5
        with:
          context: ./backend/
          build-args: |
            "PYTHON_VERSION_BUILD=${{ vars.PYTHON_VERSION_BUILD }}"
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/volunteers_backend:latest
